apiVersion: apps/v1
kind: Deployment
metadata:
  name: knag-users-api-deployment
  labels:
    app.kubernetes.io/name: knag-users-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/component: users-api
    app.kubernetes.io/part-of: knag
    app.kubernetes.io/managed-by: helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: knag-users-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300    
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      labels:
        app.kubernetes.io/name: knag-users-api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: knag-users-api
        image: {{.Values.image.repository}}:{{ .Values.image.tag }}
        env:
        - name: SPRING_DATA_MONGODB_HOST
          value: {{ .Values.db.host | default (include "mongodb.fullname" .Subcharts.mongodb) | quote}}
        - name: SPRING_DATA_MONGODB_PORT
          value: {{ required "Missing database port" .Values.db.port | quote}}
        - name: SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE
          value: {{ required "Missing value: authentication-database" .Values.db.name | quote}}
        - name: SPRING_DATA_MONGODB_DATABASE
          value: {{ .Values.db.name | quote}}
        - name: SPRING_DATA_MONGODB_USERNAME
          value: {{ .Values.db.username | quote}}
        - name: SPRING_DATA_MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: knag-users-db-secret
              key: mongodb-passwords
              optional: false
        - name: MAILGUN_APIURL
          value: {{ required "Missing mailgun api url" .Values.mailgun.apiUrl | quote}}
        - name: MAILGUN_APIKEY
          value: {{ required "Missing mailgun api key" .Values.mailgun.apiKey | quote}}
        - name: MAILGUN_DOMAIN
          value: {{ required "Missing mailgun api domain" .Values.mailgun.domain | quote}}
        - name: MAILGUN_SENDER
          value: {{ required "Missing mailgun api sender" .Values.mailgun.sender | quote}}
        - name: RECAPTCHA_KEY_SITE
          value: {{ required "Missing recaptcha site key" .Values.recaptcha.siteKey | quote}}
        - name: RECAPTCHA_KEY_SECRET
          value: {{ required "Missing recaptcha secret" .Values.recaptcha.secretKey | quote}}
        - name: KNAG_KEY_PRIV
          value: {{required "Missing rsa private key" .Values.rsaKey.priv | quote}}
        - name: KNAG_KEY_PUB
          value: {{required "Missing rsa public key" .Values.rsaKey.pub | quote}}


        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: "/actuator/health/liveness"
            port: 3000
          initialDelaySeconds: 1
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: "/actuator/health/liveness"
            port: 3000
          initialDelaySeconds: 1
          periodSeconds: 5      